### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized.github.io#1]
As the modpack is not limited to CF anymore, it could use a simple static website.

- [ ] Pick a theme 
   - [Bootstrap](https://startbootstrap.com/?showPro=false)
   - [Jekyll](https://jekyllrb.com/docs/themes/)
- [ ] Copy to a separate branch
- [ ] Decide on the most important content
  - [ ] Download button
    - CF (CF, MultiMC, GDLauncher)
    - Others in a small link
    - Very simplified install instructions, with link to full ones
        - Get CurseForge Launcher/Modrinth Launcher/Vanilla installer
        - Click install on FO
        - Play the game
  - [ ] Video
  - [ ] Main features
    - Performance
    - OF parity/shaders
    - Minor tweaks
    - Latest Minecraft
    - "Works everywhere" - in every server and in different launchers
    - Open development
    - Fabric mods support
    - Helpful community
  - [ ] Few screenshots
  - [ ] Support links
    - Wiki
    - Discord
    - Curseforge
    - Rate modpack
    - Mastodon
- [ ] Reconsider the information density on CF and GH readme
- [ ] Client-side localization support 
   - [Jekyll](https://tuananh.net/2014/08/13/localization-with-jekyll/) 
   - [banana-i18n](https://github.com/wikimedia/banana-i18n)
   - [VuePress](https://vuepress.vuejs.org/) (suggested by a deleted commenter)
   - https://gillesleblanc.wordpress.com/2016/01/27/localization-with-jekyll/ 
   - https://forestry.io/blog/creating-a-multilingual-blog-with-jekyll/
   - https://blog.logrocket.com/implementing-localization-svelte/
   - Similar to Iris?
- [x] Advertise in main menu text/MultiMC description

[Design inspiration](https://www.labymod.net/en)

**Comment by RaptaG** [comment]
I decided to learn HTML, in some months I'll be done with the courses, so if needed I'll help!

**Comment by osfanbuff63** [comment]
Ironically, I've been working on so many Jekyll websites recently, so if you'd like I would love to help!

**Comment by Madis0** [comment]
> Ironically, I've been working on so many Jekyll websites recently, so if you'd like I would love to help!

The main reason this has been on hiatus is localization. Do you know a plugin that would be simple to use, detect language automatically (with the possibility of override) and work with GitHub?

**Comment by osfanbuff63** [comment]
> > Ironically, I've been working on so many Jekyll websites recently, so if you'd like I would love to help!
> 
> The main reason this has been on hiatus is localization. Do you know a plugin that would be simple to use, detect language automatically (with the possibility of override) and work with GitHub?

Most of them use [GitHub Actions](https://jekyllrb.com/docs/continuous-integration/github-actions/) and assign GitHub Pages to build off of the `gh-pages` branch, but the source files are in `master`. This allows for any plugins we want, and with GitHub Actions, it's still simple to set up ([here's](https://github.com/osfanbuff63/osfanbuff63.github.io) one of them if you want to take a look).

The [`minimal-mistakes`](https://github.com/mmistakes/minimal-mistakes) theme has built-in localization ([source](https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#starting-fresh)). That theme will work for almost all things you want (if you want it to look a bit different, we can always make a custom skin :P). Otherwise, [this tutorial](https://medium.com/@desfocado/how-to-make-jekyll-multilingual-c13e74c18f1c) looks like it might work, but looks complicated. On the plugin end, [`jekyll-language-plugin`](https://github.com/vwochnik/jekyll-language-plugin) or [`jekyll-multiple-languages-plugin`](https://github.com/kurtsson/jekyll-multiple-languages-plugin) look pretty good. I need to do more research about those however.

**Comment by Madis0** [comment]
Alright. Could you join our Discord so we can discuss this whenever I intend to do it? I don't exactly know when, but it would be nice to have you there when that happens :stuck_out_tongue: https://discord.gg/yxaXtaQqdB

**Comment by Madis0** [comment]
Done. https://download.fo
